config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end

  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/views/shared/_admin_dropdown.html.haml
%li
  = link_to 'Admin Dashboard', admin_root_path
  %li.divider

app/views/shared/_alerts.html.haml
- if flash[:notice]
  = js add_gritter(flash[:notice], image: :success, nodom_wrap: true, sticky: false)
- elsif flash[:error]
  = js add_gritter(flash[:error], image: :error, title: 'Error', nodom_wrap: true, sticky: false)
- elsif flash[:alert]
  = js add_gritter(flash[:alert], image: :error, title: 'Alert', nodom_wrap: true, sticky: false)

app/views/shared/_audit_log_tab.html.haml
%li{class: "#{active?(audit_logs_path)}"}
  = link_to 'Audit Log', audit_logs_path

app/views/shared/_employee_nav_items.html.haml
%li{class: "#{active?(posts_path)}"}
  = link_to 'Entries', posts_path
%li{class: "#{active?(new_post_path)}"}
  = link_to 'Submit Hours', new_post_path, id: 'new_post_from_nav'

app/views/shared/_nav.html.haml
.logo
  %h1 Time tracker
- if current_user
  %ul.nav.nav-tabs.custom-nav
    %li{class: "#{active?(root_path)}"}
      = link_to '', root_path, class: 'glyphicon glyphicon-home'
    = render 'shared/employee_nav_items' if employee?
    = render 'shared/audit_log_tab' if admin?

    %li.dropdown.pull-right
      %a.dropdown-toggle.glyphicon.glyphicon-cog{"data-toggle" => "dropdown", :href => "#"}
        %strong.caret
      %ul.dropdown-menu
        = render 'shared/admin_dropdown' if admin?
        %li
          = link_to 'Log out', destroy_user_session_path, method: :delete